// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEHcp_Bs_WNZ72x_G1KfmfqbogFeS8FKk',
    appId: '1:916880720010:web:6084453d350fc56f85ed73',
    messagingSenderId: '916880720010',
    projectId: 'fir-ayatask',
    authDomain: 'fir-ayatask.firebaseapp.com',
    storageBucket: 'fir-ayatask.firebasestorage.app',
    measurementId: 'G-7M7P0GQ7S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_elPKyXC49UjwUdWdHsVNmozp7H4Gdi8',
    appId: '1:916880720010:android:15bc4892bd52469885ed73',
    messagingSenderId: '916880720010',
    projectId: 'fir-ayatask',
    storageBucket: 'fir-ayatask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuHqZbVFV6uqd-Cb4ES9Y7S119hx-bueQ',
    appId: '1:916880720010:ios:8a5f52bb80c0055285ed73',
    messagingSenderId: '916880720010',
    projectId: 'fir-ayatask',
    storageBucket: 'fir-ayatask.firebasestorage.app',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuHqZbVFV6uqd-Cb4ES9Y7S119hx-bueQ',
    appId: '1:916880720010:ios:8a5f52bb80c0055285ed73',
    messagingSenderId: '916880720010',
    projectId: 'fir-ayatask',
    storageBucket: 'fir-ayatask.firebasestorage.app',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEHcp_Bs_WNZ72x_G1KfmfqbogFeS8FKk',
    appId: '1:916880720010:web:70b8f949d33d2a3a85ed73',
    messagingSenderId: '916880720010',
    projectId: 'fir-ayatask',
    authDomain: 'fir-ayatask.firebaseapp.com',
    storageBucket: 'fir-ayatask.firebasestorage.app',
    measurementId: 'G-SBFZF0L904',
  );
}
